version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: regional_monitoring
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgis/postgis:15-3.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: regional_monitoring
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
